port: 3000
appLogLevel: warn
appLogSize: 31457280
jtt808:
  port: 3001
  heartBeatInterval: 600000
database:
  storage: database.sqlite
sysadmin:
  username: sysadmin
  password: sysadmin
session:
  secrets: abcd.1234